
function handHtml(){
    if( JSHander.type == 1){
        JSHander.html  = JSHander.html +  "	<style>.ui-bar-b, .ui-page-theme-b .ui-bar-inherit, html .ui-bar-b .ui-bar-inherit, html .ui-body-b .ui-bar-inherit, html body .ui-group-theme-b .ui-bar-inherit {background-color: #f9364d;border-color: #f9364d;color: #ffffff;text-shadow: 0 0 0 #eeeeee;font-weight: bold;}.ui-page-theme-b .ui-btn, html .ui-bar-b .ui-btn, html .ui-body-b .ui-btn, html body .ui-group-theme-b .ui-btn, html head + body .ui-btn.ui-btn-b, .ui-page-theme-b .ui-btn:visited, html .ui-bar-b .ui-btn:visited, html .ui-body-b .ui-btn:visited, html body .ui-group-theme-b .ui-btn:visited, html head + body .ui-btn.ui-btn-b:visited {background-color: #f9364d;border-color: #f9364d;color: #ffffff;text-shadow: 0 0 0 #f3f3f3;}.ui-btn.ui-checkbox-off:after, .ui-btn.ui-checkbox-on:after {-webkit-border-radius: .1875em;border-radius: .1875em;background-color: #f9364d;}.ui-btn-icon-left:after, .ui-btn-icon-right:after, .ui-btn-icon-top:after, .ui-btn-icon-bottom:after, .ui-btn-icon-notext:after {background-color: #f9364d ;background-color: rgba(249, 54, 77,1) ;background-position: center center;background-repeat: no-repeat;-webkit-border-radius: 1em;border-radius: 1em;}.ui-page-theme-b .ui-btn:hover, html .ui-bar-b .ui-btn:hover, html .ui-body-b .ui-btn:hover, html body .ui-group-theme-b .ui-btn:hover, html head + body .ui-btn.ui-btn-b:hover {background-color: #f9364d;border-color: #f9364d;color: #ffffff;text-shadow: 0 0 0 #f3f3f3;}.ui-header.ui-bar-b {display: none;}.ui-body-a, .ui-page-theme-a .ui-body-inherit, html .ui-bar-a .ui-body-inherit, html .ui-body-a .ui-body-inherit, html body .ui-group-theme-a .ui-body-inherit, html .ui-panel-page-container-a {background-color: #f9f9f9;    border-color: #f9f9f9; color: #333333; text-shadow: 0 1px 0 #f3f3f3;    text-shadow: 0 0px 0 #f3f3f3; padding: 0px;        -webkit-box-shadow: inset 0 0px 0px /*{global-box-shadow-size}*/ rgba(0,0,0,.2) /*{global-box-shadow-color}*/;  }legend, .ui-input-text input, .ui-input-search input {margin: 0px;height: 40px;-webkit-box-shadow: inset 0 1px 1px 1px /*{global-box-shadow-size}*/ rgba(0,0,0,.2) /*{global-box-shadow-color}*/;     border-radius: 50px;-webkit-box-shadow: inset 0 1px 1px /*{global-box-shadow-size}*/ rgba(0,0,0,1.2) /*{global-box-shadow-color}*/;}legend, .ui-input-text input,.ui-input-search input {margin: 0px;-webkit-box-shadow: inset 0 1px 1px 1px /*{global-box-shadow-size}*/ rgba(0,0,0,.2) /*{global-box-shadow-color}*/;  border-radius: 15px; margin: 0px;-webkit-box-shadow: inset 0 1px 9px 2px /*{global-box-shadow-size}*/ rgba(2,1,1,0.2) /*{global-box-shadow-color}*/;border-radius: 15px;}</style>";
        
    }else {
        
          JSHander.html  =   JSHander.html + " 888888888888888";
        
    }

}
handHtml();
